### PR TITLE
sv - Swedish translation

### PR DESCRIPTION
**Pull request by Liggliluff**
Added Swedish translation, and added it to locales/config.json

### CODE REVIEW

**Comment by DJDavid98** [comment]
Hi, thank you very much for your contribution!

There's a few additional changes that need to be made manually before the language is fully supported in the app, so it's usually easier for folks to go through Crowdin for the translations, and I can take care of the additional code changes myself.

If you could add these through the Crowdin UI at https://crowdin.com/project/hammertime/sv-SE I'd appreciate it, if not I'll have to open a separate PR with your commit to make the rest of the changes.

**Comment by DJDavid98** [comment]
Oh, I realized I'll have to open a new PR regardless since I can't edit the branch in your fork. I'm happy to include the changes though, but I'll do it in #36

**Comment by Liggliluff** [comment]
Sorry, I didn't realise that was the process. You did a quick job with this.

**Comment by DJDavid98** [comment]
@Liggliluff I'm not sure what the best place to contact you is, but there's a handful of new strings that need translating. If you are still open to helping with translations, I'd ask that you please join the site's Discord server so that you can be notified when your help would be needed alongside all the other translators for the project. The link is in the repository README.

**Pull request merged**
